feeds:
  - url: "https://www.reddit.com/r/navimumbai/new/.rss" 
    category: "local"
  - url: "https://timesofindia.indiatimes.com/rssfeeds/-2128936835.cms"
    category: "local"
  - url: "https://www.mid-day.com/Resources/midday/rss/mumbai-news.xml"
    category: "local"
  - url: "https://indianexpress.com/feed/"
    category: "local"
  - url: "https://news.google.com/rss/search?q=Navi+Mumbai&hl=en-IN&gl=IN&ceid=IN:en"
    category: "local"
